name: Announce calls
on:
  schedule:
    # 8th to the 14th of each month at 9am.
    - cron: '0 9 8-14 * *'
    # Thusdays at 7am.
    - cron: '0 7 * * 4'
    # Trigger more for testing.
    - cron: '*/15 * * * *'

jobs:
  build-message:
    runs-on: ubuntu-latest
    steps:
      # We use `date +\%u` below in combination with the schedule cron rules
      # above to ensure these only run on the days they are meant to. 
      - name: Build message
        run: |
          TZ=UTC
          DAY=$(date +\%u)
          case "${DAY}" in
              7)    echo "MESSAGE=The #farmOS monthly community call is today at 2pm Eastern. All are welcome! https://farmos.org/community/monthly-call/" >> $GITHUB_ENV ;;
              4)    echo "MESSAGE=The #farmOS weekly dev call is today at 12pm Eastern. All are welcome! https://meet.jit.si/farmos-dev" >> $GITHUB_ENV ;;
          esac
    outputs:
      message: ${{ env.MESSAGE }}
  announce-call:
    uses: ./.github/workflows/create-message.yml
    needs:
      - build-message
    if: ${{ needs.build-message.outputs.message }}
    with:
      message: ${{ needs.build-message.outputs.message }}
    secrets: inherit
